spring:
  application:
    name: RATINGMICROSERVICE
  data:
    mongodb:
      uri: mongodb://localhost:27017
      database: micro
  config:
    import: optional:configserver:http://localhost:8086
server:
  port: 8082
# eureka:
#   instance:
#     prefer-ip-address: true
#   client:
#     fetch-registry: true
#     register-with-eureka: true
#     service-url:
#       defaultZone: http://localhost:6565/eureka
